# Generated by Django 5.2.8 on 2025-11-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='College Management System', max_length=200)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('email_port', models.IntegerField(default=587)),
                ('email_host_user', models.CharField(blank=True, max_length=200)),
                ('email_host_password', models.CharField(blank=True, max_length=200)),
                ('sms_api_key', models.CharField(blank=True, max_length=200)),
                ('chat_bot_name', models.CharField(default='AI Support', max_length=100)),
                ('chat_default_response', models.TextField(default="I'm sorry, I didn't understand that. You can ask about your profile, attendance, notifications, subjects, or sessions.")),
            ],
        ),
    ]
