# Generated by Django 5.2.8 on 2025-11-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='preset_questions',
            field=models.TextField(default='Show my profile, Check attendance, Any notifications?'),
        ),
    ]
