# Generated by Django 5.2.8 on 2025-11-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_systemsettings_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_id_number',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate ADM-XXXX', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_id_number',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate STF-XXXX', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate STU-XXXX', max_length=20, null=True, unique=True),
        ),
    ]
