# Generated by Django 5.2.8 on 2025-11-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_fill_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstaff',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave end date (optional)', null=True),
        ),
        migrations.AddField(
            model_name='leavereportstudent',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave end date (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='date',
            field=models.DateField(),
        ),
    ]
