# Generated by Django 5.2.8 on 2025-11-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_leavereportstaff_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Government-issued ID (Admin only)', max_length=20, null=True, unique=True),
        ),
    ]
