# Generated by Django 5.2.8 on 2025-12-02 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_delete_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('feedback_reply', 'Feedback Reply'), ('result_published', 'Result Published'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
