# Generated by Django 5.2.8 on 2025-12-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_useralert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAlert',
        ),
    ]
