# Generated by Django 5.2.8 on 2025-12-03 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_delete_useralert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('leave', 'Leave'), ('feedback', 'Feedback'), ('result', 'Result'), ('announce', 'Announcement')], max_length=10)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
