# Generated by Django 5.2.8 on 2025-12-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_dashboardcounter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardCounter',
        ),
    ]
