# Generated by Django 4.2.27 on 2025-12-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_chatbotconversation_chatbotintent_chatbotmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotconversation',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatbotIntent',
        ),
        migrations.RemoveField(
            model_name='chatbotmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='ChatbotConversation',
        ),
        migrations.DeleteModel(
            name='ChatbotMessage',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
