# Generated by Django 4.2.27 on 2025-12-04 04:42

# main_app/migrations/0018_dashboardnotification_useractivitylog.py
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_chatbotconversation_user_delete_chatbotintent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('leave_student', 'Student Leave Request'), ('leave_staff', 'Staff Leave Request'), ('feedback_student', 'Student Feedback'), ('feedback_staff', 'Staff Feedback'), ('result_update', 'Result Updated'), ('admin_notification', 'Admin Notification'), ('leave_reply', 'Leave Reply'), ('feedback_reply', 'Feedback Reply')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dashboardnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='main_app_das_recipie_xxx'),
        ),
        migrations.AddIndex(
            model_name='dashboardnotification',
            index=models.Index(fields=['notification_type'], name='main_app_das_notif_xx'),
        ),
    ]