# Generated by Django 4.2.27 on 2025-12-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_admin_id_alter_attendance_id_and_more'),
        ('main_app', '0019_dashboardnotification_useractivitylog'),
    ]

    operations = [
    ]
