# Generated by Django 4.2.27 on 2025-12-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_merge_20251204_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RenameIndex(
            model_name='dashboardnotification',
            new_name='main_app_da_recipie_3a0718_idx',
            old_name='main_app_das_recipie_xxx',
        ),
        migrations.RenameIndex(
            model_name='dashboardnotification',
            new_name='main_app_da_notific_26d588_idx',
            old_name='main_app_das_notif_xx',
        ),
    ]
